### ISSUE TITLE
gulp 4 error

### ISSUE THREAD

**Issue by mbadr1993** [electric-eloquence/gulp4-run-sequence#1]
this task not working with gulp 4 
TypeError: gulp.on(...).on(...).on(...).on(...).start is not a function

**Comment by e2tha-e** [comment]
Hello @mbadr1993 . Thanks for your interest in gulp4-run-sequence!

I'm afraid `.on()` and `.start()` are not gulp4-run-sequence methods. Consequently, this issue is off-topic. Nonetheless, I can try to point you in the right direction.

`.on()` and `.start()` are not documented gulp methods, either in v3 or v4. They are, however, methods on the [Orchestrator](https://github.com/robrich/orchestrator) class, a dependency of gulp 3, and its superclass. gulp 4 does not depend on, nor inherit from, Orchestrator.

If you find that upgrading from gulp 3 to 4 presents an overwhelming refactor, you might want to try [gulp 3 with long-term support](https://github.com/electric-eloquence/gulp).
